name: "1. Update Issue Title"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  update-title:
    runs-on: ubuntu-latest
    if: true # Disable this job
    steps:
      - name: Update issue title
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          PREFIX="PRO"

          YEAR=$(date +%y)
          PADDED_NUM=$(printf "%04d" "$ISSUE_NUMBER")
          IDENTIFIER="${PREFIX}-${YEAR}${PADDED_NUM}"

          OLD_TITLE="${{ github.event.issue.title }}"
          NEW_TITLE="${IDENTIFIER}: ${OLD_TITLE}"

          gh issue edit "$ISSUE_NUMBER" --title "$NEW_TITLE" --repo "${{ github.repository }}"
