name: "3: Auto Format Issue Title"
run-name: Auto format issue using composite action

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  issues: write

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  format_title:
    runs-on: ubuntu-latest
    if: true # Disable this job
    steps:
      - uses: actions/checkout@v4
      - name: Format issue title
        uses: ./.github/actions/format-issue-title
        with:
          # prefix: PRO # change this as per your convention
          prefix: ${{ vars.PROJECT_PREFIX }}
