name: "3: Auto Format Issue Title"
run-name: Auto format issue using composite action

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  format_title:
    runs-on: ubuntu-latest
    steps:
      - name: Format issue title
        uses: .github/actions/format-issue-title@main
        with:
          prefix: PRO # change this as per your convention
